services:
  db:
    image: mongo
    container_name: ${DB_CONTAINER}
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DB_VOLUME}:/data/db
  
  express:
    image: mongo-express
    container_name: ${EXPRESS_CONTAINER}
    restart: always
    ports:
      - ${EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@${DB_CONTAINER}:${DB_PORT}/
      - ME_CONFIG_MONGODB_SERVER=${DB_CONTAINER}
    depends_on:
      - db
  
  api:
    build:
      context: .
    image: localhost:7002/acnhmate-api:${TAG}
    container_name: ${API_CONTAINER}
    restart: always
    ports:
      - ${API_PORT}:80
    environment:
      - AnimalCrossingDatabaseSettings__ConnectionString=mongodb://root:password@${DB_CONTAINER}/?authSource=admin&directConnection=true&ssl=false
      - AnimalCrossingDatabaseSettings__DataBaseName=acnhDB
    depends_on:
      - db

volumes:
  elastic_volume:
    driver: local